import './natty-fetch.spec'
import './util.spec'
import './ajax.spec'
import './event.spec'
import './storage.spec'
import './plugin.spec'
import './plugin.soon.spec'
import './plugin.loop.spec'
// import './plugin.customRequest.spec'
import './simple.spec'
import './private-promise.spec'
import './timeout-with-self-concurrent.spec'